// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myqqhabctewuqitvnnaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cXFoYWJjdGV3dXFpdHZubmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzE1OTAsImV4cCI6MjA2NzMwNzU5MH0.K5fZn4twW2oWoTeWRAMwui_jAqGb0dRnl_yqoMEw1ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});